create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

// 데이터 입력
insert into member(name) values('spring');
insert into member(name) values('spring2');

// 데이터 확인
select * from member;

